name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Sanitize npm config (remove auth, force public registry)
        shell: bash
        run: |
          echo "Before cleanup:" && npm config list || true
          rm -f $HOME/.npmrc .npmrc || true
          npm config delete "//registry.npmjs.org/:_authToken" --location=user || true
          npm config delete "//registry.npmjs.org/:_authToken" --location=global || true
          npm config delete "//npm.pkg.github.com/:_authToken" --location=user || true
          npm config delete "//npm.pkg.github.com/:_authToken" --location=global || true
          npm config set registry https://registry.npmjs.org/ --location=user
          npm config set always-auth false --location=user
          echo "After cleanup:" && npm config list || true
        env:
          NODE_AUTH_TOKEN: ""
          NPM_TOKEN: ""

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ""
          NPM_TOKEN: ""
      - run: npm run build
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out
          
      - uses: actions/deploy-pages@v4
